### ISSUE TITLE
Disable/Enable Staging does not update staging icons for many parts

### ISSUE THREAD

**Issue by Theysen** [shadowmage45/SSTULabs#287] opened 2016-04-18 22:03 UTC
- CM parts: Enable/Disable Staging for parachutes not working in VAB/SPH and Inflight right-click menu
- all parts with Enable/Disable Staging **(except SC-GEN-PDC Custom Decoupler - works normally)** not working in VAB/SPH and Inflight right-click menu

The logs attached - no idea if they are for use in this case - are taken after clicking both Parachute and Decouple on the SC-C CM and SC-C-SM right click menu in the VAB. Maybe they say something about the issue. 

https://www.dropbox.com/sh/1ac31lk1gdzv9cd/AAAXo2uaDRQ5lwF23-HF0Kt5a?dl=0
^ (works now by clicking, I don't need the Link function from GitHub)

**Comment by shadowmage45** [comment] 2016-04-18 22:33
If you are referring to what I think you are, the lack of the staging icons being added/removed -- this is a stock bug that I can do nothing about.  Basically if a part has a staging icon assigned to it that is not what the module expects it will leave it in the staging bar.

Edit: Additionally, the SSTU pods have TWO possible staging actions; a parachute and a decoupler.  I don't think the stock staging system can even deal with that kind of a setup.

Now the real question is -- does the staging properly work when 'enabled', and does it properly not work when 'disabled' ?

**Comment by Theysen** [comment] 2016-04-18 22:49
Well for the parachutes I can say: No. They are disabled by default to appear in the staging bar so as Enable Parachute in Staging does nothing staging there won't activate a chute. Having at least the chutes working in the staging bar might be more intuitive for gameplay. (same for fairing deploy, currently mandatory to right click deploy)
- EDIT: Enabling Parachute in staging will work properly when firing the stage with the CommandPodIcon. (Sorry for the report then, I think this behaviour is intended.)

For all other parts I tested so far it's basically the same behaviour. I used a fairing base to replicate and tested it inflight. Clicking Disable Staging or Enable staging didn't change the result, it decoupled upon staging anyways, disabling didn't make the icon disappear. This is what I reported above.

**Comment by shadowmage45** [comment] 2016-04-18 22:53
Thanks for the update.

Disabling the staging through the right click menu should actually disable staging for the module/function that you are adjusting; though it will -not- update the icon (that is the stock bug I was referring to).

So, if the parts are not respecting the staging enabled/disabled that you are setting, I will look into this sometime this week.

**Comment by shadowmage45** [comment] 2016-04-18 23:19
After some brief investigation I can say that at least the command pod parts are working as intended.  Both the decoupler and the parachute modules obey their 'staging enabled' settings.

The fairings as well appear to work as intended; if you 'enable decoupler staging' they -do- properly respond to staging actions by decoupling the payload.  For these I will investigate changing the module setup to also allow for enable/disable of the fairing deploy staging.

As noted however, the staging icon does not change when toggling staging or when they are all disabled.  This comes back to the stock 'bug' that I mentioned; honestly I think it just gets confused when there are multiple stage-able modules on the same part.

Are there any specific parts where they are not obeying their staging settings (keep in mind I'm not talking about the icon; only the actual action when you press the staging button)?

**Comment by Theysen** [comment] 2016-04-20 09:57
Ok, maybe I didn't express myself clearly enough about what I was actually trying to say.

When you place the Stack Decoupler you can make the Staging Icon disappear in the Staging Bar by clicking the according right click menu button. It then doesn't decouple inflight as expected. 

When you place a Radial Booster Decoupler you have the same option in the right click menu but clicking it doesn't make the staging icon disappear so it will stage in flight no matter what. 

So the question is: does it make sense to have the option to disable staging in the right click menu if it doesn't change the behaviour anyway, neither in the VAB nor inflight at all? Just to keep the menus intuitive and cleaned up. 

- OR is it not working because something broke / the stock bug you mentioned?

**Comment by shadowmage45** [comment] 2016-04-20 14:21
```
Ok, maybe I didn't express myself clearly enough about what I was actually trying to say.

When you place the Stack Decoupler you can make the Staging Icon disappear in the Staging Bar by clicking the according right click menu button. It then doesn't decouple inflight as expected.

When you place a Radial Booster Decoupler you have the same option in the right click menu but clicking it doesn't make the staging icon disappear so it will stage in flight no matter what.

So the question is: does it make sense to have the option to disable staging in the right click menu if it doesn't change the behaviour anyway, neither in the VAB nor inflight at all? Just to keep the menus intuitive and cleaned up.

    OR is it not working because something broke / the stock bug you mentioned? 
```

As mentioned, I can do nothing about the staging icons; that is a stock function that has problems when a part has more than one stageable module.  It is stock code and not under my control.  From my testing though the toggles work fine on the parts it is merely the icon that does not update properly.

All the parts that you mention are effected by it because they all have multiple stageable modules. 
- RBDC has both engines and decoupler module. 
- IPA - Has multiple decouplers.
- Command pods -- have decoupler + parachutes. 
- Interstage Decoupler has multiple decouplers and an engine module. 
- Resizable fairings have both a fairing module and a decoupler.

I will not remove the option to edit the staging; had too much bitching about them not being there before I added them; which is why I added those options in the first place (or rather enabled them in the config files, it is all stock code that I have no access to).

Sadly I push the KSP engine way beyond what it is intended to do and there are going to be artifacts and unresolvable problems because of it.  Even more so  because I do not have source access for KSP;  even if I wanted to fix (read: hack around) some of these problems, I cannot because I have no way to know what/where the problem is or what the potential solution or workaround might be.

I will gladly accept pull-requests with solutions to the problem if you manage to figure it out though.

**Closed as completed** 2017-07-16 18:14 UTC
Labels: Bug, wontfix, Stock Bug
