### ISSUE TITLE
SRB-U and SRB-US

### ISSUE THREAD

**Issue by Nightside101010** [shadowmage45/SSTULabs#567] opened 2017-09-27 13:22 UTC
Is it intentional to have both SRB-U and SRB-US parts? 
If so, what is the difference?

It seems like SRB-US might be a WIP version that slipped into the release... There are graphical problems and placing the part makes my log angry.

SRB-U works great though.

![screenshot14](https://user-images.githubusercontent.com/20480557/30915315-48760bd6-a34b-11e7-91a1-58fabaa0dc78.png)

Not tested for mod incompatibilities, please let me know if you need more info.

**Comment by shadowmage45** [comment] 2017-09-27 14:08
~~Hmm... should only be the SRB-U part; the US was a git-merge failure (rather I tried to switch branches while KSP was running, which screwed things up as the SSTUTools.dll was locked for in-use).~~

Apparently that is not the case, as the release only has the SRB-U in the .zip.  Appears to be a case of old install data being left (should usually completely delete mod folders before installing a new version).

**Comment by taterkerman** [comment] 2017-09-27 17:00
I see only SRB-U in the engines section. Where are you seeing SRB-US?

**Comment by shadowmage45** [comment] 2017-09-27 17:10
I -think- that he merged the new install with his old folders.  That would explain the second/incorrect part config file (the last release did have an SRB-US, but it was removed for this release).

At least that is what it looks like currently, as I have confirmed that there is only an SRB-U in the current master branch (which was used to pack the release).

**Comment by Nightside101010** [comment] 2017-09-27 17:10
I deleted, re-unzipped and reinstalled and SRB-US.cfg is gone! 
I may have overwritten SSTU (without deleting the old version as I usually do) when installing the latest version. 
@shadowmage45 it might be helpful to add "delete old version" to the installation instructions, since many mods specifically DON'T want you to delete the folder when installing new versions.
I guess this is resolved, thanks for all the support!

**Closed as completed** 2017-09-27 17:10 UTC
Labels: Bug
