### ISSUE TITLE
ISDC Interstage decoupler - can't recolor thrusters

### ISSUE THREAD

**Issue by Temeter** [shadowmage45/SSTULabs#628] opened 2017-11-20 08:08 UTC
As it says, thrusters can't be recolered. I'd say making the white take the primary outer hull color and the black the inner hull color would be the easiest way to set it up? (some silvery specular stoff for the small nozzle would be neat tho)

On a minor note, the thruster box has some z-fighting with the bottom of the decoupler going on.
Veeeeeery minor thing.^^

**Comment by blowfishpro** [comment] 2017-11-20 08:21
I think this is a duplicate of #625

**Comment by Temeter** [comment] 2017-11-20 08:23
In fact, it is ;)

**Closed as completed** 2017-11-20 08:23 UTC
