### ISSUE TITLE
Lack of stock SAS functionality on crewed spacecraft and service modules.

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#271] opened 2016-03-20 18:56 UTC
The various command pods are assumed to have "probe core" SAS functionality, but none are listed in the part descriptions. Right now, a few of the tanks have this notation, but none of the capsules do. 

The LC pods all require crew---but have the all SAS functionality if ANY crew is aboard (doesn't require the crew to be a pilot, unlike stock command pods---not a bad thing, IMO, but different from stock).

The command pods have all the SAS functionality (not noted in the part description), but it is a little odd. As long as they are attached to something else, they hold the appropriate position, but alone (say for reentry) thy are all offset from the desired heading (prograde, retrograde, etc.).

**Comment by shadowmage45** [comment] 2016-03-20 19:41
The issue regarding the off-vector heading hold is a stock problem that I've been unable to find the cause of, or solution for.  Something with how stock calculates the COM for a single-part vessel.

List of parts to investigate / make uniform:
SC-A-CM
SC-A-CMX
SC-A-SM
SC-B-CM
SC-B-CMX
SC-B-SM
SC-B-ICPS
SC-B-HUS
SC-C-OM
SC-C-DM
SC-C-SM
SC-C-SMX
SC-E-FS
SC-E-FSX
LC2-POD
LC3-POD
LC5-POD
SC-TANK-MUS-CB
SC-TANK-MUS-ST

Will be investigating all of those parts; they should all either have a fully functional unmanned capability, or zero unmanned capability.

**Comment by shadowmage45** [comment] 2016-03-20 20:13
All parts listed above have had ModuleCommand and ModuleSAS (at level 3) added.

This is separate from reaction wheel capability, which will be further addressed in a future balancing pass.

TODO: Update part descriptions where applicable.  This is also part of a larger detailing pass that needs to be made over the parts.

**Comment by taterkerman** [comment] 2016-03-21 03:08
Ah ha! It was not that I was using an old version. Test this in _career_... they all work with full SAS functionality in _sandbox_, but not career.

**Closed as completed** 2016-03-27 14:40 UTC
Labels: Enhancement, Next Update, Fixed In Dev
