### ISSUE TITLE
The landing Legs

### ISSUE THREAD

**Issue by Mecripp** [shadowmage45/SSTULabs#1] opened 2015-07-27 19:43 UTC
Deploy the legs in VAB, I can't retract them or even click on the part any more  won't let even open debug or forgot how, I am on Linux.

**Comment by shadowmage45** [comment] 2015-07-27 19:56
Is this the single landing leg, or the leg quads?

It is more than likely a collider problem, as the fuel tanks have colliders across the open area that could prevent clicking on the leg if you offset the leg inside of the tank too far;  I -tried- to expand the colliders to stick out a small amount from the tank so they are still clickable, but I'm not sure if this change made it to the single leg (I know it works with the leg-quads).

In upcoming release the legs will be integrated into the fuel tanks as a part variant; so this may not matter in the long run.

**Comment by shadowmage45** [comment] 2015-07-27 22:58
Upon further examination, this might be caused by the 'decompress' code that I added (as I am seeing the no-retract behavior in the VAB); never checked on its function in VAB, and I don't think the flight-update-tick code runs in the VAB, so it never finishes the decompress cycle, and thus never retracts.

(they -should- still retract fine in flight; if not, plz let me know)

Thanks for catching this one, will have it fixed for next release.

**Comment by Mecripp** [comment] 2015-07-28 18:04
It's all the Leg and sorry don't remember the name of the part but there was only one that had legs and tank like lander part that the legs would even deploy on in VAB but after picking any of the parts that have legs on them, I can move the part or click on it again my guess if, I could get my Debug menu to open it's null when, I try and click on it ?

**Comment by shadowmage45** [comment] 2015-07-28 18:27
Aye, I found the issue / have fixed it in dev code.  I was forgetting that I needed to manually update the animation state in the VAB as I had separated the FixedUpdate() call, and didn't link it all back up properly.

Hopefully I'll have an updated release in a day or two with the fix (and integrating the legs into the fuel tanks as a part-variant).

**Comment by shadowmage45** [comment] 2015-08-04 00:11
Fixed in latest dev release

**Closed as completed by shadowmage45** 2015-08-04 00:11 UTC
