### ISSUE TITLE
textures

### ISSUE THREAD

**Issue by clanec15** [shadowmage45/SSTULabs#344] opened 2016-08-02 00:23 UTC
the f*****\* textures arent working,...
¡PLEASE,SOMEONE,HELP!

**Comment by shadowmage45** [comment] 2016-08-02 00:26
Logs?
Screenshots of gamedata folder?
List of mods?

How do you expect to be helped if we have no information as to what the problem is?

**Comment by clanec15** [comment] 2016-08-02 01:50
Ok,i have a screenshot of the game,that work?

**Comment by shadowmage45** [comment] 2016-08-02 02:02
Its a place to start at least, might give me enough info to tell what is going on.

You should be able to drag screenshots directly into the text box for your reply and it will show up with your post.

**Comment by clanec15** [comment] 2016-08-02 02:43
Ok,tomorrow I send the image of the game

**Comment by clanec15** [comment] 2016-08-02 16:36
the textures of the parts are in White literally

**Comment by shadowmage45** [comment] 2016-08-02 16:40
Then I will need a screenshot of your GameData folder layout to make sure you have the mod installed correctly, as it sounds like it is not setup properly.

**Comment by clanec15** [comment] 2016-08-02 16:47
![issue](https://cloud.githubusercontent.com/assets/20783305/17337082/71bf00d6-589e-11e6-845e-4703c6cbed28.jpg)

**Comment by clanec15** [comment] 2016-08-02 16:49
![issue 2](https://cloud.githubusercontent.com/assets/20783305/17337156/ba639ae0-589e-11e6-99fc-ce8992cef25d.jpg)

**Comment by clanec15** [comment] 2016-08-02 16:51
and?

**Comment by clanec15** [comment] 2016-08-02 16:51
is anything i can do?

**Comment by shadowmage45** [comment] 2016-08-02 16:52
Thanks for the screenshots; those both look to be correct for a basic installation.

Would you mind posting/attaching your KSP.log file?  (can be found at .../Steam/steamApps/common/KerbalSpaceProgram/KSP.log) -- this should be able to tell me what problems are occuring when the game is loading the models/textures (if it is even loading them).

**Comment by shadowmage45** [comment] 2016-08-02 16:53
Although, I'm also noticing that you do not have ModuleManager installed;  it is necessary in order to run SSTU (and many other mods).  You should have a ModuleManager_xxx.dll file in your GameData folder.

This problem alone will cause all sorts of problems with SSTU, and is why I include it in the distribution.

**Comment by clanec15** [comment] 2016-08-02 16:54
![issue 3](https://cloud.githubusercontent.com/assets/20783305/17337355/837891c4-589f-11e6-8188-16ef10d08c77.jpg)

**Comment by clanec15** [comment] 2016-08-02 16:57
i can't find the KSP.log

**Comment by clanec15** [comment] 2016-08-02 16:57
is this?

**Comment by shadowmage45** [comment] 2016-08-02 16:58
Sadly, I will need the log in order to do any further investigation.

And that module-manager setup is not correct and may be causing problems.  You should only have a single ModuleManager.dll, and it should be in the root GameData folder.

**Comment by clanec15** [comment] 2016-08-02 17:00
![issue 4](https://cloud.githubusercontent.com/assets/20783305/17337533/4f79b046-58a0-11e6-872f-c816df770d7d.jpg)

**Comment by clanec15** [comment] 2016-08-02 17:00
i can't upload the text file

**Comment by clanec15** [comment] 2016-08-02 17:03
![issue 5](https://cloud.githubusercontent.com/assets/20783305/17337600/abb15de6-58a0-11e6-9d22-7ab4e5ee694e.jpg)

**Comment by clanec15** [comment] 2016-08-02 17:05
![issue 6](https://cloud.githubusercontent.com/assets/20783305/17337660/f5400bd8-58a0-11e6-9872-791a861508f1.jpg)

**Comment by clanec15** [comment] 2016-08-02 17:06
is this the correct installation?

**Comment by clanec15** [comment] 2016-08-02 17:08
[KSP.docx](https://github.com/shadowmage45/SSTULabs/files/397629/KSP.docx)

**Comment by clanec15** [comment] 2016-08-02 17:08
i think is thaht is the KSP.log

**Comment by clanec15** [comment] 2016-08-02 17:17
hello
anyone there?

**Comment by shadowmage45** [comment] 2016-08-02 17:17
The image you posted above with the station part -- those are supposed to look that way.  The parts are unfinished and are only included for testing purposes.  They will not have textures for at least a few weeks

Are the engines and other parts (command pods) missing their textures, or is it just the station parts?

Also, have some patience; I'm at work at the moment, nor do I get paid for doing this stuff.

**Comment by clanec15** [comment] 2016-08-02 17:20
no and the re-entry command pod and i dont know what other part

**Comment by clanec15** [comment] 2016-08-02 17:20
ok,well thanks

**Comment by clanec15** [comment] 2016-08-02 17:20
i can make you the textures

**Comment by shadowmage45** [comment] 2016-08-02 17:25
Not an issue; closing.  Those station parts are not supposed to have textures.

And thanks for the offer, but they are nowhere near ready for texturing yet, the models are not even finished.

**Closed as completed by shadowmage45** 2016-08-02 17:25 UTC
