### ISSUE TITLE
Debug warning on SSTU-GEN-ISDC

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#282] opened 2016-04-17 21:59 UTC
`[Error]: Cannot find fx group of that name for decoupler` appears 4 times when instantiating the part in the editor.  I'm not sure exactly what's causing this of if it's avoidable, but I figured I'd post here anyway.

E: Also appears every time the part is updated.

**Comment by shadowmage45** [comment] 2016-04-18 14:38
Noted... thought I had fixed the FX stuff for all decoupler enabled parts, but I may have missed one (or the plugin is doing something funny...)

**Comment by shadowmage45** [comment] 2016-04-18 17:07
Hmm.. this seems like it might be related to having both 'old' and 'new' style FX definitions in that part;  all of the engine stuff is defined through EFFECTS nodes, while the decoupler FX are defined through the old XXX = decouple style definitions.

Will have to sit down and do a bit more investigation on this as I'm unsure if they are intended to work together.

For reference the standard decoupler FX -are- defined in that part (just like all the others), but KSP seems to not be loading them properly.

**Comment by shadowmage45** [comment] 2016-04-22 01:18
After some... puzzling... investigation I have narrowed this down to being caused by RealPlumes.  The RBDC is also effected by this as it has RP configurations as well.

As I am using RP to do the effects for the decoupler jettison motors; real-plumes deletes all existing fx on the part before adding its plumes.

Disabling/deleting the RealPlumes-ShipCore.cfg patch will 'fix' the missing decoupler fx-group issues.

I'll likely have to run a patch to re-add the sound in a FINAL or AFTER[zzz-RealPlumes] block to ninja-add the sound-fx-group back in...

**Comment by shadowmage45** [comment] 2016-04-22 01:26
fixed with FINAL block; still runs under a NEEDS so that it doesn't duplicate the fx in stock setups

**Comment by blowfishpro** [comment] 2016-04-23 21:46
My understanding was that using FINAL is discouraged outside of personal patches because it prevents anything from being edited by another mod.  Use of zzz-whatever is pretty common I think.

**Comment by shadowmage45** [comment] 2016-04-23 22:49
Noted;  I'll figure out where RP is doing the deletion stuff an come up with an appropriate AFTER block.

**Comment by shadowmage45** [comment] 2016-04-26 15:32
Updated to run in an AFTER[zRealPlume] block

**Closed as completed** 2016-04-30 14:42 UTC
Labels: Bug, Next Update, Fixed In Dev
