### ISSUE TITLE
Consumers not receiving propellant, despite being directly attached with fuel lines

### ISSUE THREAD

**Issue by TheGentlemoon** [shadowmage45/SSTULabs#332] opened 2016-07-12 22:57 UTC
Happens in the VAB, the game doesn't seem to recognize that the consumer and propellant are right next to each other. Even if you put a fuel line directly on the engine and fuel source it still doesn't work.
![image 30](https://cloud.githubusercontent.com/assets/20428463/16786392/8470a230-4862-11e6-9745-01e613a7c599.png)

**Comment by shadowmage45** [comment] 2016-07-12 23:42
Try toggling the tanks 'enable crossfeed' setting and see what the report says (the problem goes away in my dev setup).

The stock engineer report stuff has always been terrible at finding problems and false reports on stuff that is not a problem (such as 'Decoupler is installed backwards' showing up for all of the CM's).

Marking this as 'stock bug', as there is literally zero that I can do regarding the stock engineer tools  reporting / misreporting.

I believe the root cause of this is enabling the radial-crossfeed setup in KSP's physics settings (which I have done to enable fuel-line-less radial tanks);  Likely you would see the same false-reports if you added the crossfeed module to the stock tanks.  If this ^^ can be confirmed, it should be filed as a bug on the stock bug tracker so that it can be fixed at the source.

The tanks and engines work fine in flight, and at least MechJeb reports proper staging sequence and dV (KER or others untested as I don't use them, but have not heard of any other problems with them (yet)).

However, if anyone else has any more information on to the cause/solution of this problem I'm open to potential solutions/workarounds (as long as they're not too hacky).  Some confirmation on if the issue exists with the crossfeed module on stock tanks could also help in getting it fixed on KSPs end of things.

**Comment by TheGentlemoon** [comment] 2016-07-12 23:53
Hi, thanks for the answer, the fix you mentioned worked. Another thing I noticed was that on some occasions adding a stock fuel line fixed the "problem" while other times it doesn't, very strange. One more thing, when enabling crossfeed on the tank, it goes away, but disabling it doesn't bring the problem back. Any idea as to why that happens? I'll go ahead and file a report on the stock tracker aswell, Thanks again!

**Closed as completed** 2016-07-13 01:05 UTC
Labels: Bug, Stock Bug
