### ISSUE TITLE
Made a station and upon launch it flew into space, and I had to quit game.

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#342] opened 2016-08-01 14:43 UTC
Title says it all.
[kerby 1.craft.zip](https://github.com/shadowmage45/SSTULabs/files/394050/kerby.1.craft.zip)

[KSP.log.zip](https://github.com/shadowmage45/SSTULabs/files/394052/KSP.log.zip)

**Comment by shadowmage45** [comment] 2016-08-01 14:54
I'm afraid I'm going to need a bit more info than that, as the title really doesn't say it all.

What kind of craft, what parts were on it, how were they configured, and are there any other mods involved?  (sorry, can't try out the craft file until sometime next week).  

What exact steps are needed to duplicate the problem? (As I launched tons of stations yesterday and certainly none of them just flew off or caused any exceptions).

None of the exceptions in the log are from SSTU, so whatever is causing the problem is part of the stock code.  Doesn't mean that one of SSTU's parts aren't the cause, merely that the problem is not directly caused by the SSTU plugin.

There are also a couple of exceptions/errors at the very start of your log that I have no idea what they are from, that appear to be OSX errors:

```
[ERR 08:24:17.843] Couldn't open /Users/merrick/Applications MFB/KSP_osx 1.1.3 SSTU test/KSP 113 bare sstu.app/Contents/Plugins/3DConnexionWrapperU5.bundle/Contents/MacOS/3DConnexionWrapperU5, error: dlopen(/Users/merrick/Applications MFB/KSP_osx 1.1.3 SSTU test/KSP 113 bare sstu.app/Contents/Plugins/3DConnexionWrapperU5.bundle/Contents/MacOS/3DConnexionWrapperU5, 2): Library not loaded: /Library/Frameworks/3DconnexionClient.framework/Versions/A/3DconnexionClient
  Referenced from: /Users/merrick/Applications MFB/KSP_osx 1.1.3 SSTU test/KSP 113 bare sstu.app/Contents/Plugins/3DConnexionWrapperU5.bundle/Contents/MacOS/3DConnexionWrapperU5
  Reason: image not found

[WRN 08:24:17.845] [SpaceNavigatorMac]: Could not initialize device.
/Users/merrick/Applications MFB/KSP_osx 1.1.3 SSTU test/KSP 113 bare sstu.app/Contents/Plugins/3DConnexionWrapperU5.bundle/Contents/MacOS/3DConnexionWrapperU5
```

Are those 'normal', or ??

I would say your first problem would be to clean up those errors, whatever they are.

**Comment by shadowmage45** [comment] 2016-08-01 14:57
## Additional information from forum post:

I opened a new issue (not well titled, sorry) and included a craft and log file (zipped).

I made a craft with the large torus, a COS hub, and a station core, with an Orion attached so I could test docking ports. I hit launch, and the thing flew into space by itself, lol, and I could not hi map view, etc, had to quit KSP.

Only mods are SSTU, KJR and hyperedit. I had planned on popping the station into orbit with HE, but it flew into space before I could ever do that. Next testing I will just launch the stuff, but I was being lazy.

**Comment by shadowmage45** [comment] 2016-08-01 22:33
Indeed - I had not properly (re) set the names on the docking port transforms for the HUB-COS, so it is not surprising that it was having problems.

Have properly renamed the docking transforms, added proper control transforms, and am testing the attached .craft file now.  With any luck it will work :)

**Comment by shadowmage45** [comment] 2016-08-01 22:37
And... I am happy to report that the test craft works fine now.

Additionally all of the 'target port XXX' and 'control from port XXX' functions also work :)

Fix will be available with the next update (likely later this evening).

**Comment by taterkerman** [comment] 2016-08-02 00:07
Here's the most recent craft file. Helped to have torus as the root part. I'm unsure about the OS X issues, KSP otherwise working fine.
[Auto-Saved Ship.craft.zip](https://github.com/shadowmage45/SSTULabs/files/394988/Auto-Saved.Ship.craft.zip)

**Comment by shadowmage45** [comment] 2016-08-02 00:15
Thanks, testing it out now.  

I got your first craft file to load fine after I fixed up the hub transform names; so hopefully this is a related issue that is already fixed.  If not, well, at least I'll have something to test/investigate :)

**Comment by shadowmage45** [comment] 2016-08-02 00:22
First good news is that I can duplicate a problem with the craft provided (large torus w/tks module below).

The second good? news is that I cannot duplicate the problem with a craft that I make using those same parts; so it is likely related to something saved in the .craft file, which I can actually dig into in depth.

Chances are that this is caused by one of the other issues that I've already fixed; going to go through the craft file quickly though to see what it could potentially be, and compare it to one that I put together with the current code.

**Comment by shadowmage45** [comment] 2016-08-02 00:25
And... that was quick.  Near the top of the .craft file there is an improper attach-node name, that is causing things to wig-out when the craft is reloaded (as the node doesn't exist on the part itself).

This improper name was being caused by some config fields that weren't flagged as public, and thus were reverting to the code-defaults rather than the data passed into it from the config file.

Good news is that it is definitely fixed, and I'll be pushing out an update with this fix in it shortly :)

**Comment by shadowmage45** [comment] 2016-08-02 01:35
Should be fixed with the latest release; please let me know if it is not.

**Closed as completed by shadowmage45** 2016-08-02 01:35 UTC
